---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf # extensible package of M4 macros that produce shell scripts to automatically configure software source code packages
  - aria2 # lightweight multi-protocol & multi-source command-line download utility
  - bash-completion # auto-complete git
  - chromedriver # WebDriver is an open source tool for automated testing of webapps across many browsers
  # - doxygen # Source code documentation and analysis tool
  # - docker # open platform for developers and sysadmins to build, ship, and run distributed applications
  - DNSMasq # provides network infrastructure for small networks: DNS, DHCP, router advertisement and network boot
  # - gettext
  # - gifsicle # Gifsicle is a command-line tool for creating, editing, and getting information about GIF images and animations.
  - git
  - go # Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
  # - gpg
  # - hub
  # - httpie # CLI HTTP client, user-friendly curl replacement with intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.
  # - iperf3 # A TCP, UDP, and SCTP network bandwidth measurement tool
  # - libevent # an event notification library
  # - sqlite # implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
  - mongodb
  # - mcrypt # allows developers to use a wide range of encryption functions
  # - nmap # utility for network discovery and security auditing
  - node # JavaScript runtime built on Chrome's V8 JavaScript engine
  # - nvm # Node Version Manager - Simple bash script to manage multiple active node.js versions
  - ssh-copy-id # OpenSSH is the premier connectivity tool for remote login with the SSH protocol
  # - cowsay
  # - readline # provides a set of functions for use by applications that allow users to edit command lines as they are typed in
  # - openssl
  # - pv # Pipe Viewer is an Open Source tool to monitor the progress of data through a pipeline between any two processes, giving a progress bar, ETA, etc.
  - wget # package for retrieving files using HTTP, HTTPS and FTP
  # - composer # Dependency Manager for PHP
  # - docker-compose # Compose is a tool for defining and running multi-container Docker applications
  # - docker-machine-nfs # Activates NFS on docker-machine
  # - dockutil # command line tool for managing dock items
  - git-extras # GIT utilities -- repo summary, repl, changelog population, author commit percentages and more
  - mas # Mac App Store command line interface
  # - mercurial # distributed source control management tool
  - npm
  # - phpmd
  # - php-code-sniffer
  # - php-cs-fixer
  # - phpunit
  # - php70
  # - php70-intl
  # - php70-imagick
  # - php70-mcrypt
  # - tmux # lets you switch easily between several programs in one terminal
  - tree # recursive directory listing command that produces a depth indented listing of files
  # - wrk # Modern HTTP benchmarking tool
  - yarn
  # - zsh # Zsh is a shell designed for interactive use, although it is also a powerful scripting language.

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  # - fing # Download link keeps getting changed, d'oh!
  - firefox
  - google-chrome
  # - handbrake
  # - licecap
  # - limechat
  # - macvim
  # - sequel-pro
  # - skitch
  - slack
  # - sublime-text
  # - transmit
  # - vagrant
  # - virtualbox
  - filezilla
  - sourcetree # GUI for GIT
  - spotify
  - spotify-notifications
  - atom # Free code editor
  - phpstorm # Paid code editor
  - google-backup-and-sync # Former google drive
  - skype
  - franz # free messaging app, that combines chat & messaging services into one application: https://meetfranz.com/
  - thunderbird # email client
  - vlc # Video player
  # - teamviewer
  # - inkscape # vector software
  # - gimp # pixel software
  # - mamp # apache mysql php
  - avast-security # Free anti-virus
  - keka # archiver
  - keepassx # password manager
  # utilities
  - alfred # Productivity application for Mac OS X, which boosts your efficiency with hotkeys, keywords and text expansion: https://www.alfredapp.com/
  - cheatsheet # Just hold the ⌘-Key a bit longer to get a list of all active short cuts of the current application: https://www.mediaatelier.com/CheatSheet/
  - coconutbattery # Shows you live information about the battery in your Mac and iOS device: http://www.coconut-flavour.com/coconutbattery/
  - flux # Makes the color of your computer's display adapt to the time of day, warm at night and like sunlight during the day.
  - easyfind # Improves search on mac
  - itsycal # Adds tiny menu bar calendar to clock: https://www.mowglii.com/itsycal/
  - spectacle # Move and resize windows with ease

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
